---
title: "Probability Theory"
---

Assignment I:

```{r}
pscope <- 0.3
pscope_time <- 0.2
Pnscope_time <- 0.6

```

```{r}
p_time_and_scope <-  pscope * pscope_time

p_time_and_nscope <- (1-pscope) * (1-Pnscope_time)

p_ntime_and_scope <- pscope * (1- pscope_time)

p_ntime_and_nscope <- (1 -pscope) * (1-Pnscope_time)

cat("P(T ∩ S) =", p_time_and_scope, "\n")

cat("P(T ∩ NS) =", p_time_and_nscope, "\n")

cat("P(NT ∩ S) =", p_ntime_and_scope, "\n")

cat("P(NT ∩ NS) =", p_ntime_and_scope, "\n")

```

Assignment II:

Using the Venn diagram above, answer the following questions:

 1-What is the percentage of customers using all three devices?:
      
```{r}
p_customers_three_devices <- 0.5
p_customers_three_devices
```
 2-What is the percentage of customers using at least two devices?  

```{r}
P_customers_two_devices = (7.3/100 + 3.3/100 + 8.8/100)*100
P_customers_two_devices
```

3-What is the percentage of customers using only one device?

```{r}
P_customers_one_device = (27.8/100 + 10/100 + 42.3/100) * 100
P_customers_one_device

```
Assignment III:

```{r}
p_B_A  <- 0.97
p_B_nA <- 0.01
p_A <- 0.04
p_nA <- 1 - p_A

p_B <- p_B_A * p_A + p_B_nA * p_nA

p_nA_B <- (p_B_nA * p_nA) / p_B
p_A_B <- (p_B_A * p_A) / p_B

cat("P(B) =", p_B, "\n")
cat("P(A'|B) =", p_nA_B, "\n")
cat("P(A|B) =", p_A_B, "\n")

cat("These results show that in case the alarm is triggered, there is a possibility of about",p_nA_B *100 ,"% that the product is flawless and a probability of",p_A_B*100, "% that the product is faulty.")
```
