{
  "hash": "0e7324833e8a6cd615f64332ac995e32",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n\n::: callout-note\nYou can delete everything in here and start fresh.\n:::\n1-\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_04df741874faf581c8dabe786d6f1e0a'}\n\n```{.r .cell-code}\nlibrary(dagitty)\nlibrary(ggdag)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> \n#> Attaching package: 'ggdag'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> The following object is masked from 'package:stats':\n#> \n#>     filter\n```\n:::\n\n```{.r .cell-code}\ncollider <- dagify(\n  P ~ S_AB ,\n  P ~ S_CD,\n  coords = list(x = c(S_CD = 3, P = 2, S_AB = 1),\n                y = c(S_CD = 1, P = 0, S_AB = 1))\n)\n\n# Plot DAG\nggdag(collider) \n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_638324df8fb96cf2ba7b47ad3e0a9a4b'}\n\n```{.r .cell-code}\ncustomer_sat <- readRDS(\"D:/TU Hamburg/Semester_5/Causal Data Science for Business Analytics/Causal_Data_Science_Data/Causal_Data_Science_Data/customer_sat.rds\")\nView(customer_sat)\n```\n:::\n\n\n2.1\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_f504f31727c8826d01dd25c10a11a06c'}\n\n```{.r .cell-code}\nlm_customers <- lm(satisfaction ~ follow_ups, data = customer_sat)\nsummary(lm_customers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = customer_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n:::\n\n\n\n2.2:\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-4_516db2bd855a316fbb2961a454b17a2e'}\n\n```{.r .cell-code}\nlm_customers_account_for_subscription <- lm(satisfaction ~ follow_ups + subscription, data = customer_sat)\nsummary(lm_customers_account_for_subscription)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = customer_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n3- It seems that the follow_ups with account to subscription has higher correlation with satisfaction, compared with follow_ups only according the adjusted R-squared value. Furthermore, the P-value of the regression between the satisfaction and the follow_ups with account to subscription is lower. Additionally, the Estimate value changed from -3.3093 to 2.1944, which change totally the relation from decreasing to increasing.\n\n\n4-\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-5_54fad5b7b85193d0c869cb56b9160460'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\ncustomers_ncond <- ggplot(customer_sat, aes(x = satisfaction , y = follow_ups)) +\ngeom_point() +\nstat_smooth(method = \"lm\", se = F)\n\n# Conditioning on student  \ncustomers_cond <- ggplot(customer_sat, aes(x = satisfaction, y = follow_ups,\n                            color = subscription, \n                            alpha = subscription)) +\n  geom_point() +\n  stat_smooth(method = \"lm\", se = F) +\n  scale_alpha_manual(values = c(\"subscription\" = 1, \"no_subscription\" = 0.2)) +\n  theme(legend.position = \"right\")\n\n# Plot both\ncustomers_ncond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncustomers_cond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}